---
# Many tasks will be included distribution specific
- name: Include "{{ ansible_distribution }}" tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Reboot Machine
  shell: sleep 2 && shutdown -r now "Reboot triggered from while-true-do.system-update"
  async: 1
  poll: 0
  ignore_errors: True
  become: yes
  when: wtd_system_update_autoreboot == True and wtd_system_update_needs_reboot.rc == 1

- name: Wait for Reboot
  wait_for_connection:
    timeout: 6000
    delay: 20
  when: wtd_system_update_autoreboot == True and wtd_system_update_needs_reboot.rc == 1
