---
# Many tasks will be included distribution specific
- name: Include "{{ ansible_distribution }}" tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Activate reboot handler
  command: "true"
  notify:
    - Reboot Machine
  when: wtd_system_update_needs_reboot is defined and
        wtd_system_update_autoreboot == True and
        wtd_system_update_needs_reboot.rc == 1
