---
- name: Install all updates
  yum: 
    name: "*"
    state: latest
    update_cache: yes
  when: wtd_system_update_all == True
  tags:
    - update

- name: Install security updates
  yum:
    name: "*"
    state: latest
    security: yes
    update_cache: yes
  when: wtd_system_update_security == True and wtd_system_update_all != True
  tags:
    - update
    - security
