---
# ansible_distribution="RedHat" specific tasks
- name: Install Dependencies
  yum:
    name: "yum-utils"
    state: present
  tags:
    - update

- name: Install Package Updates
  yum:
    name: "*"
    state: latest
    security: "{{ wtd_system_update_security_only }}"
    update_cache: True
  tags:
    - update

- name: Check for required Reboot
  command: needs-restarting -r
  ignore_errors: True
  register: wtd_system_update_needs_reboot
  changed_when: wtd_system_update_needs_reboot.rc != 0
  failed_when: wtd_system_update_needs_reboot.rc != 1 and
               wtd_system_update_needs_reboot.rc != 0
  tags:
    - update
